VehicleLookupApi/VehicleLookupApi/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using VehicleLookupApi.Areas.HelpPage.ModelDescriptions;
using VehicleLookupApi.Areas.HelpPage.Models;

namespace VehicleLookupApi.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

VehicleLookupApi/VehicleLookupApi/Controllers/ClientController.cs
using SearchService;
using Services;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace VehicleLookupApi.Controllers
{
    [CORSHeader]
    public class ClientController : Controller
    {
        /// <summary>
        /// Displays Jquery Client
        /// </summary>
        /// <returns></returns>
        public ActionResult JQuery()
        {
            return View();
        }

        /// <summary>
        /// Displays Angular Client
        /// </summary>
        /// <returns></returns>
        public ActionResult Angular()
        {
            return View();
        }

        /// <summary>
        /// Displays Demo Features
        /// </summary>
        /// <returns></returns>
        public ActionResult Features()
        {
            return View();
        }

        [System.Web.Http.HttpGet]
        public JsonResult Search(String searchCriteria)
        {
            var btree = (BTree<Vehicle>)HttpContext.Application[ApplicationKeys.ModelSearchTree];
            var suggestionList = btree.Children(searchCriteria);

            var a = new { total = suggestionList.Count, results = suggestionList.Select(vh => vh.Model).ToList() };
            return Json(a, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// This generates a sample error and demonstrates the use of Elmah for error logging and administration
        /// URL : /elmah.axd. 
        /// Elmah access can be restricted to authorized users e.g  https://stackoverflow.com/questions/6778881/how-can-i-restrict-remote-access-to-elmah
        /// </summary>
        [System.Web.Http.HttpGet]
        public virtual void Error(String id)
        {
            throw new Exception("Unhandled Exception");
        }

        [System.Web.Http.HttpGet]
        public virtual ActionResult SearchPerformance()
        {
            return View();
        }

    }
}

VehicleLookupApi/VehicleLookupApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @{ ViewBag.Title = "Vehicle API Help";}

    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

    <script src="~/Scripts/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js" type="text/javascript"></script>

</head>


<body>

    <div class="navbar" style="background-color:#3875d8">

        @Html.ActionLink((String)ViewBag.Title, "Index", "Help", new { area = "" }, new { @class = "navbar-brand navMenuItem"})

        <a href="~/v1/Vehicles" class="navbar-brand navMenuItem" >Get V1 </a>
        <a href="~/v2/Vehicles" class="navbar-brand navMenuItem" >Get V2 </a>


        @Html.ActionLink("Jquery Client", "JQuery", "Client", new { area = "" }, new { @class = "navbar-brand navMenuItem" })
        @Html.ActionLink("Angular Client", "Angular", "Client", new { area = "" }, new { @class = "navbar-brand navMenuItem" })
        @Html.ActionLink("Features", "Features", "Client", new { area = "" }, new { @class = "navbar-brand navMenuItem" })
        @Html.ActionLink("GenerateError", "Error", "Client", new { area = "" }, new { @class = "navbar-brand navMenuItem" })

        <a href="~/elmah.axd" class="navbar-brand navMenuItem" >View Error Logs </a>

        @Html.ActionLink("SearchPerformance", "SearchPerformance", "Client", new { area = "" }, new { @class = "navbar-brand navMenuItem" })

        <a href="http://byronweather.azurewebsites.net/" class="navbar-brand navMenuItem" >Another Angular Demo </a>

    </div>

    <div style="margin-left: 20px;margin-right: 20px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @ViewBag.Title</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>