ResponsiveAngularApp/Welrs Admin UI/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Welrs_Admin_UI.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        //[HttpGet]
        //[Authorize]
        //[ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            ViewBag.MainPageId = 1;
            return View("DashboardIndex");
        }
    }
}

ResponsiveAngularApp/Welrs Admin UI/Controllers/HCAssignmentController.cs
using AdminUI.Common;
using AdminUI.DataProvider;
using AdminUI.Models;
using AdminUI.Models.HCAssignment;
using AdminUI.Models.Queue;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Welrs_Admin_UI.Controllers
{

   // [WelrsAuthorize] 
    public class HCAssignmentController : Controller
    {
        //[OutputCache(Duration = 86400 ,Location=OutputCacheLocation.Client)]
        public ActionResult Index()
        {
            ViewBag.MainPageId = 3;
            ViewBag.ShowControlSection = true;
            return View("HCAIndex");
        }

        [HttpGet]
        [ValidateHeaderAntiForgeryToken]
        public ActionResult FailedQueItems()
        {
            var prov = HCAssignmentDataProviderFactory.GetProvider();

            List<MSH> msh = prov.GetMSH();

            var tree = TreeViewHelper.Transform(msh);

            var ret = new TreeViewData()
            {
                MSHData = msh,
                TreeData = tree,
                AssignCodes = prov.GetAssignmentCodes(),
                TreeConfig = new TreeConfig()
            };

            return Json(ret, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [ValidateHeaderAntiForgeryToken]
        public String HL7Data(int msh_id)
        {
            var prov = HCAssignmentDataProviderFactory.GetProvider();
            return prov.GetHL7Message(msh_id);
        }

        [HttpPost]
        [ValidateHeaderAntiForgeryToken]
        public ActionResult Save(int MSH_ID, string Note, List<ChangeSetData> ChangeSet)
        {
            var prov = HCAssignmentDataProviderFactory.GetProvider();
            String errorMessage = "";
            String username = System.Web.HttpContext.Current.User.Identity.Name;
            var success = prov.Save(username, MSH_ID, Note == null ? "" : Note, ChangeSet, out errorMessage);
            return Json(new ResponseStatus()
            {
                Success = success == true ? ResponseStatus.ApiResponseStatus.Success : ResponseStatus.ApiResponseStatus.Failure,
                ErrorMessage = errorMessage
            });
        }
    }
}

ResponsiveAngularApp/Welrs Admin UI/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Welrs_Admin_UI.Controllers
{
    public class QueueController : Controller
    {
        // GET: Queue
        //[HttpGet]
        //[Authorize]
        //[ValidateAntiForgeryToken]
        public ActionResult Index()
        {
            ViewBag.MainPageId = 2;
            return View("QueueIndex");
        }
    }
}

ResponsiveAngularApp/Welrs Admin UI/Views/_ErrorLayout.cshtml
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!-- Required Stylesheets -->
    <link href="~/scriptsfontscss/css/bootstrap.css" rel="stylesheet">
    <link href="~/scriptsfontscss/css/site.css" rel="stylesheet">

</head>

<body>

        <div id="Content" class="DaContentContainer">
            @RenderBody()
        </div>

</body>
</html>

ResponsiveAngularApp/Welrs Admin UI/Views/_MainLayout.cshtml
@using System.Web.Optimization
@{
    var username = HttpContext.Current.User.Identity.Name.ToString();
}

<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <!-- Required Stylesheets -->
    <link href="~/scriptsfontscss/css/bootstrap.css" rel="stylesheet">
    <link href="~/scriptsfontscss/css/site.css" rel="stylesheet">

</head>

<body>
    <div id="MainContainer" class="DaMainContainer">
        <nav class="navbar navbar-default">
            <div class="">
                <div class="navbar-header">
                    <text class="navbar-brand">WELRS Admin Utility</text>
                </div>

                <ul class="nav navbar-nav">
                    <li class="@(ViewBag.MainPageId == 1 ? "active":"")"><a href="@Url.Action("Index","Dashboard")">Dashboard</a></li>
                    <li class="@(ViewBag.MainPageId == 2 ? "active":"")">
                        <a href="@Url.Action("Index", "Queue")">Queue Management</a>
                    </li>
                    <li class="@(ViewBag.MainPageId == 3 ? "active":"")"><a id="MainHCAUrl" href="@Url.Action("Index","HCAssignment")">Health Condition Assignment</a></li>
                </ul>

                @if (ViewBag.ShowControlSection == true)
                {
                    <button class="btn btn-info btn-large ControlRegion " data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-shopping-cart"></i><text id="ShoppingCart"></text></button>
                }

                <span class="UserNameMarginTop">&nbsp;&nbsp; @username</span>

            </div>
        </nav>
        <div id="Content" class="DaContentContainer">
            @RenderBody()
        </div>
    </div>
</body>
</html>